language: php
php:
- 7.2
- 7.3
branches:
  only: master
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests
matrix:
  fast_finish: true
notifications:
  on_success: never
  on_failure: always
deploy:
  provider: heroku
  app: uhd-student-portal
  api_key:
    secure: WEd2v3qXMD8auZfC5RgHhFdyNXXFt3qK3NdO2EmvaVQTb3pHilTzsdvlMtPSWQ4l2AfMNYEqOAFL59fIY6TC8Y4AxH0b5WBYd1JTr6cNPddk0zw9Tl+lDmOwPyoNvz4V879svPqtsaCK1Q6nCJ1Ok0VRJ7VYjJIQFr6S+mIzKOtqILB7fdSvjnHP2KDXwmCGo9KWjX+wkMBuD5hwR3PxHS1KKKMgGGdNggkUwPPin4oj938id3z5iIqnuBgb5V5+Jzazx/LMqDEhY4WM+nRrk1Su403F4FYq6PpYJGeip5Y/faj366hmhmyWgctIVOYyCLRV7sUU0jcrVqkGekTiwlvv/9FRyT10OHjcH+/NIkgTyyeqWDPPE89gx6e2mb2KVeT++mzeK3iWL+IoZsKFidjJMRRBITUolTyjYyeQjb362/KHmKU08Gi+tzxiVcOUDJ8XNZCgbk1GNOLwARoSxOg4RkLnnmWBlVC6NavWylmWg8vM3bk/+SiWhH5vU74x8HWUnsF6BZVxLQ9qym0u60YXSgUvCISGybo5wJrwJTP2ZIo1JhYEiQZP7Ym9PgWTX+MK5Lnhb0oMfP1LLWXC8HdpY0IGf3ZwQojpKoHBPbcS/Tq0uhrI9+q2Azwt82+Th2J21OIMqnmtYNanv0WpRRZLOEoCZyCT07gRcmpjCEo=
  on:
    repo: briandcase/SoftwareEngineeringProject
  skip_cleanup: true
